name: Build and push Docker image

# Run on push to main branch and on PRs targeting main.
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    name: Build and push image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up QEMU (optional for cross-arch)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          # repository on Docker Hub
          tags: |
            jram17/express-demo:latest
            jram17/express-demo:${{ github.sha }}
            jram17/express-demo:${{ github.ref_name }}
          # optionally enable platforms if you want multi-arch builds
          # platforms: linux/amd64,linux/arm64
